#!/usr/bin/env python
from collections import defaultdict
import sys, string
sys.setrecursionlimit(10000)

truthers = set([])
liars = set([])
accuse_dict = defaultdict(list)

def main():
	if(len(sys.argv) == 1):
		file = 'input.txt'
	else:
		file = sys.argv[1]
	f = open(file)
	people_count = int(f.readline())
	
	for each_inp in xrange(0, people_count):
		accuser_accused_count = string.split(f.readline())
	 	for each_candi in range(0, int(accuser_accused_count[1])):
			accused = f.readline().strip()
			accuse_dict[accuser_accused_count[0]].append(accused)
	
	# The meat. For every accuser, figure out if which group they belong to,
	# and recurse through their anybody their accused accuses.
	for accuser in accuse_dict:
		for accused in accuse_dict[accuser]:
			recurse_accused(accuser, accused)
	
	len_truthers = len(truthers)
	len_liars = len(liars)
	if (len_truthers > len_liars):
		print len_truthers, len_liars
	else:
		print len_liars, len_truthers
			

def recurse_accused(accuser, accused):
	# If we know both accused/accusee are in different pools, no more work needed.
	if 	accuser in truthers and accused in liars or \
		accused in truthers and accuser in liars: 
		return

	# Know accuser is a liar, which means the accused must be a truther.
	if accuser in liars and accuser not in truthers:
			truthers.add(accused)
	# Know accused is a truther, which means the accuser is a liar
	elif accused in truthers and accused not in liars:
		liars.add(accuser)
	else:
		truthers.add(accuser)
		liars.add(accused)

	for each_user in accuse_dict[accused]:
		recurse_accused(accused, each_user)





if __name__== "__main__":
	main()
